### ISSUE TITLE
2 Updates to the Analytics

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website-API#120]
- we don't want the FE to know what various categories of analytics there are, nor which graphs should be shown for which analytics category.

- Therefore, we should have a endpoint that gives back the list of categories there are:
```
GET /analytics_categories

[
 {title: 'Community', id: 'community', endpoint: '/community_analytics'},
 {title: 'Economy', id: 'economy', endpoint: '/economy_analytics'},
 ...
 {title: 'Other Social', id: 'other', endpoint: '/other_social_analytics'},
 {title: 'Website', id: 'website', endpoint: '/website'}
]

- title will be used for the Label.
- id will be used for FE links (eg 'other social' analytics is at the route '/analytics/other'
- endpoint is the BE endpoint
- data shape is an array to dictate which order the analytics should be displayed in
```

- Also, for specific analytic category endpoint, it should look something like:
```
 GET /economy_endpoints with optional timeframe as params:
 
 [
  {
    "title": "Total Coins Distributed",
    "data": {
       "2021-06-27T00:00:00Z": 54,
       "2021-06-20T00:00:00Z": 432,
       ...
    }
  },
  {
    "title": "Total Coins Distributed to Core",
    "data": { ... }
  },
  {
    "title": "Total Coins Distributed to Faucet",
    "data": { ... }
  },
  {
    "title": "Total Coins Distributed to Projects
",
    "data": { ... }
  },
]
```
- This way, the FE doesn't have to specifically know which `key` it should parse, nor does it have to have the title for each graph hardcoded.

These two changes will make it easier for us moving forward. If we decide to add/remove a particular analytics or category, we can simply do so by updating the BE.

For example, we are going to add Pinterest as one of our social media sections. So we'll probably need an analytics endpoint for that.

**Comment by angle943** [comment]
here's my second (i think better) option (things changed in bold. First data shape is changed too):

we don't want the FE to know what various categories of analytics there are, nor which graphs should be shown for which analytics category. **We also don't want the BE to have hardcoded the various categories, since new categories can be formed in the future (such as pinterest)**

Therefore, we should have a endpoint that gives back the list of categories there are:

```
GET /analytics_categories

[
 {title: 'Community', id: 'community'},
 {title: 'Economy', id: 'economy'},
 ...
 {title: 'Other Social', id: 'other'},
 {title: 'Website', id: 'website'}
]
```
- title will be used for the Label.
- id will be used for FE links (eg 'other social' analytics is at the route '/analytics/other'
- **The ID will also be used to grab the BE endpoint for that particular category (example below)**
- data shape is an array to dictate which order the analytics should be displayed in

Also, for specific analytic category endpoint, it should look something like:

**GET /analytics/economy with optional timeframe as params:**

```
 [
  {
    "title": "Total Coins Distributed",
    "data": {
       "2021-06-27T00:00:00Z": 54,
       "2021-06-20T00:00:00Z": 432,
       ...
    }
  },
  {
    "title": "Total Coins Distributed to Core",
    "data": { ... }
  },
  {
    "title": "Total Coins Distributed to Faucet",
    "data": { ... }
  },
  {
    "title": "Total Coins Distributed to Projects
",
    "data": { ... }
  },
]
```

**Comment by angle943** [comment]
heres a model example i shared: 

```
Class AnalyticsCategory:
  title: string;             // "Other Social Media"
  id: string;                // "other"
  analytics: Analytics[];


Class Analytics:
  uuid: string;              // Example, lets say this was 'test123'
  title: string;             // 'Total Coins Distributed to Core'
  dataset: AnalyticsDataset[];


Class AnalyticsDataset:
  analytics: string;        // ie 'test123'
  date: Timestamp;
  value: number;
  ```

```
GET /analytics-categories

[
 {title: 'Community', id: 'community', analytics: ['123', '124', ...]},   (these should come back as nested data instead)
 {title: 'Economy', id: 'economy', analytics: ['111', '112', ...]},
 ...
 {title: 'Other Social', id: 'other', analytics: []},
 {title: 'Website', id: 'website', analytics: []}
]


GET /analytics/123123 (uuid for 'Community')

{
  uuid: '123123';
  title: 'Community'
}


GET /analytics-dataset?analytics=123123&from=monday&to=friday     (obviously monday/friday should be proper dates)

[
 {date: 'monday', value: 56},
 {date: 'tuesday', value: 128},
 ...
]
```

**Comment by ThaDeveloper** [comment]
@angle943 I'm not sure I get exactly the requirement and how the use case will be, mostly the last part on the models. But it seems you want to be able to fetch all the analytics categories available then use the id of those categories to fetch the respective analytics. Also, have all the analytics in one model instead of the different analytics models we had?
If that's the case we don't need 3 Models, we can simply have `AnalyticsCategory` ( /analytics-categories) and `Analytics`(/analytics) which has category as foreign key.

```
Class AnalyticsCategory:
  title: string;
  id: string; 

  Class Analytics:
    uuid: string;  
    category: "website12344s"; // (query specific analytics using this id) /analytics?category=123123&from=monday&to=friday 
    value: number;
    date: Timestamp
```

**Comment by angle943** [comment]
@ThaDeveloper 
![Screen Shot 2021-06-27 at 10 27 07 PM](https://user-images.githubusercontent.com/5943963/124003564-b8979700-d99c-11eb-9cd3-ad128c8d8697.png)

With the model you presented, how will you distinguish getween `Total Coins Distributed` analytics and `Total Coins Distributed to Core` analytics? Each AnalyticsCategory can have more than one graph

**Comment by ThaDeveloper** [comment]
Isn't that the purpose of Analytics Category  to different  the different analytics? Total coins distributed is the total of core,faucet and projects?

**Comment by angle943** [comment]
Sorry @ThaDeveloper didn't see your message until now. This was what i was thinking

![Screen Shot 2021-07-03 at 8 48 49 PM](https://user-images.githubusercontent.com/5943963/124370748-5c54a180-dc40-11eb-82c9-760b74da9ba7.png)

**Comment by angle943** [comment]
@ThaDeveloper here's the link to the mocks fyi: https://www.figma.com/file/wWisZsaUf9xzkCCqlzvG3G/Analytics?node-id=1%3A4

**Comment by angle943** [comment]
btw i don't think `AnalyticsDataset` is the right word, as `dataset` refers to a collection of data points. maybe `AnalyticsData` or `AnalyticsDatapoint` is a better word for that diagram above

**Comment by ThaDeveloper** [comment]
Having to fetch from 3 different models to get one type of analytics will be a performance bottleneck, 2 models work as described above

**Comment by angle943** [comment]
@ThaDeveloper okay let me know when it is ready
