### ISSUE TITLE
Remove test requirements.txt

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website-API#13]
https://github.com/thenewboston-developers/Website-API/blob/master/requirements.txt

**Comment by vosi** [comment]
@buckyroberts this is needed for elasticbeanstalk

**Comment by fonar** [comment]
As an idea, it could be added in
.ebextensions/django.config
as a step, in containter_commands just by copying ./requirements/production.txt to ./requirements.txt

**Comment by vosi** [comment]
no, it shouldn't, beanstalk creates a venv in the process and checks for reqs.txt in the root dir, also it utilizes caching and so on
adding it to ebextensions as a command is a bad option in any sense

**Comment by fonar** [comment]
Ah, ok, prbably, just wanted to share my experince, that before, on Elastic Beanstalk Python 3.6 platform, when there was no pipenv support (and i'm usually using pipenv), this worked for me well:

  04_pipenv_requirements:
    command: "pipenv lock -r > pipenv-requirements.txt"
  05_pip_requirements:
    command: "pip install --no-cache-dir -r pipenv-requirements.txt"

so, there was no requirements.txt at all.

Bit i didn't tried it on later platforms, as starting from 'Python 3.7 running on 64bit Amazon Linux 2 platform' i just used Pipenv and no requirements.txt was needed at all, as pipenv was supported.

**Comment by vosi** [comment]
even for 3.6 and amazon linux 1 its better to create reqs.txt on the root, since python env provisioning should be run by cfn facility

**Comment by fonar** [comment]
agree, there always many ways of doing the same thing :)
