### ISSUE TITLE
Analytics endpoints are throwing errors

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Website-API#134]
Error at `/analytics_categories`, `/analytics` and `/analytics_data`

- http://api.thenewboston.com/analytics_categories
- http://api.thenewboston.com/analytics
- http://api.thenewboston.com/analytics_data

**Screenshot:**
![r2r2](https://user-images.githubusercontent.com/22790904/126539593-1c28a322-f50a-472c-909e-906532310ce8.PNG)

**Comment by ThaDeveloper** [comment]
@truyenhv We need to run below migrations in order:
1. `python3 manage.py migrate analytics zero`
2. `python3 manage.py migrate`
This can solve this issue.

**Comment by truyenhv** [comment]
Do we need to run it everytime we deploy?

**Comment by ThaDeveloper** [comment]
No just this time
