### ISSUE TITLE
App Store Model

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Website-API#136]
Build the API for App Store.
Design: https://www.figma.com/file/zbQ5xuZqAfhAlOiy9ilZlm/App-Store?node-id=300%3A4568

```python

# App

name: string;
description: string;
logo: image;
website: string;
images: AppImages[];

# AppImages

app: fk
image: Image;

```

**Comment by manishram** [comment]
Hey @angle943 how we are going to manage app overview ? https://www.figma.com/file/zbQ5xuZqAfhAlOiy9ilZlm/App-Store?node-id=220%3A2344

**Comment by angle943** [comment]
@manishram it should be stored in the BE
