### ISSUE TITLE
OpenAPI (Swagger) for API

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website-API#14]

**Comment by fonar** [comment]
@buckyroberts @vosi i have experience using drf-yasg but can't say i ever implemented 100% perfect solution using it as there was never such requirements. I see that on DRF page https://www.django-rest-framework.org/topics/documenting-your-api/
new recommended package appeared `drf-spectacular`. And in drf-yasg documentation, they recommend to use `drf-spectacular` for a new projects in this way:If you are looking to add Swagger/OpenAPI support to a new project you might want to take a look at drf-spectacular, which is an actively maintained new library that shares most of the goals of this project, while working with OpenAPI 3.0 schemas.

**Comment by itsnikhil** [comment]
#### I used `drf-yasg` it works great out of the box 
![image](https://user-images.githubusercontent.com/20350674/98083235-0d335280-1ea0-11eb-821e-61c131e06c4a.png)

**Comment by vosi** [comment]
I'd prefer lib that supports open API v3
yasg is only v2
so, i'd vote for spectacular

**Comment by fonar** [comment]
@buckyroberts  do you want this to be added exactly to Wensite-API, or to Bank & Validator?
