### ISSUE TITLE
Trusted Banks

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website-API#144]
Create a `TrustedBank` model and related `/trusted_banks` endpoint that will return a list of banks owned and managed by the core team. We will be using these banks in our client apps so that users can auto-connect to banks without having to type in the IP address and other related information.

The `TrustedBank` model will include the `ip_address`, `port`, and `protocol` fields which will be the same as the `NetworkNode` model here https://github.com/thenewboston-developers/thenewboston-python/blob/development/src/thenewboston/models/network_node.py#L12

We will use Django admin to add, edit, and delete these objects so no POST, PATCH, or DELETE endpoints are needed.

**Example Response:**
```json
[
  {
    "ip_address": "54.183.16.194",
    "port": 80,
    "protocol": "http"
  },
  {
    "ip_address": "13.233.77.254",
    "port": 80,
    "protocol": "http"
  },
  {
    "ip_address": "45.33.60.42",
    "port": 80,
    "protocol": "http"
  }
]
```

**Comment by ThaDeveloper** [comment]
@buckyroberts Is there a need for `core_team` foreign key in TrustedBank?
