### ISSUE TITLE
Combine app_store/images and app_store/apps 

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website-API#158]
Would be good if the app_store/apps contains the image urls as well

This is because it will result into a lot of api calls, i.e. 
- FE calls the `app_store/apps` to get all the apps
- For each image in each app, call the `app_store/image` to get the corresponding image

**Comment by ThaDeveloper** [comment]
@jamessspanggg Is not already implemented? Have a look below, we have image urls under /apps:
![image](https://user-images.githubusercontent.com/12385482/131547897-20e68ecd-3e2b-4271-b0c1-115b9424066f.png)
