### ISSUE TITLE
Return the fields of responsibilities and skills rather than just the pk in openings table

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website-API#172]
Currently, the responsibilities and skills are located from different table from the openings. This means that for FE, we will need to query several times to the responsibility and skills table for each opening. 

I think all the details for the responsibilities and skills should be accessible within the opening.

<img width="1149" alt="Screen Shot 2021-10-09 at 4 02 18 PM" src="https://user-images.githubusercontent.com/32864116/136649864-f73f0278-e422-40ef-9768-18190dc6a671.png">

**Comment by ThaDeveloper** [comment]
@jamessspanggg The title/description is a bit confusing, I think what you mean here is to return the fields of `responsibilities` and `skills` rather than just the pk? Openings, Responsibilities, and Skills need to be in different tables, we just need to pre-fetch all fields.

**Comment by jamessspanggg** [comment]
> @jamessspanggg The title/description is a bit confusing, I think what you mean here is to return the fields of `responsibilities` and `skills` rather than just the pk? Openings, Responsibilities, and Skills need to be in different tables, we just need to pre-fetch all fields.

yep you are correct, my bad
