### ISSUE TITLE
add query param `count` in playlists API

### ISSUE THREAD

**Issue by thesanjeevsharma** [thenewboston-developers/Website-API#195]
![image](https://user-images.githubusercontent.com/29539278/153251411-aea28179-6846-41cc-9c15-b3390114b80d.png)

For the trending tab, we only need 8 playlists. Currently, there is no way to specify the `count` of items returned in the response.

**Comment by ThaDeveloper** [comment]
@thesanjeevsharma This feature is already available under `https://api-dev.thenewboston.com/playlists?limit=1`
