### ISSUE TITLE
Endpoint for storing visitor emails

### ISSUE THREAD

**Issue by thesanjeevsharma** [thenewboston-developers/Website-API#20]
On the website, users/visitors can submit their emails which will be used for email campaigns later.

We need an endpoint for it.

[Issue on Website repo](https://github.com/thenewboston-developers/Website/issues/931)

**Comment by Eebru-gzy** [comment]
I write Javascript, I would have loved to work on this

**Comment by itsnikhil** [comment]
I want to work on this!
