### ISSUE TITLE
Team Page API Updates

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website-API#27]
For this task you will be migrating static data from the website over to the API. We will then update the website to fetch that data from the API. 

Here is the team page static data that we will be moving over to the API:
https://github.com/thenewboston-developers/Website/blob/development/src/data/teams.json

Teams page(s) - https://thenewboston.com/teams/All/Members
Docs - https://docs.google.com/document/d/1_ycBeCBYtaTDBKKN5jcaP__zDLbg5gQXoJEWmtiaHfw/edit?usp=sharing
Frontend ticket - https://github.com/thenewboston-developers/Website/issues/1269

**Comment by dhakal0kushal** [comment]
is this issue being worked on? if not can I be assigned?
