### ISSUE TITLE
Tidy up our documentation of Website-API

### ISSUE THREAD

**Issue by shaheerwasti** [thenewboston-developers/Website-API#28]
Please create file, preferably spreadsheet for listing end points or any references with details to their functionality in addition to naming convention used for input parameter along with sample response.

**Comment by sno2** [comment]
As this is Django, you should be able to go to the index root (`/`) and check out all of the routes for now.  Of course, we will probably implement a documentation later on.

**Comment by shaheerwasti** [comment]
> As this is Django, you should be able to go to the index root (`/`) and check out all of the routes for now. Of course, we will probably implement an actual documentation later on.

Gotcha!
