### ISSUE TITLE
I can't login // ~ The emails for account activation are not delivered ?

### ISSUE THREAD

**Issue by reydd** [thenewboston-developers/Website-API#40]
While creating the account the email activation are not delivered to the email account.

I've tried to create the account and the email activation are not received by my email.

**Comment by buckyroberts** [comment]
Hi @reydd - we are working on this now. Should be fixed in a week or so.

**Comment by oj-codes** [comment]
I'm experiencing this issue as of today - no email in my inbox or spam folder and get an error when trying to sign-in:

<img width="525" alt="Screen Shot 2021-02-22 at 10 15 57 PM" src="https://user-images.githubusercontent.com/297811/108798376-b25f5d00-755b-11eb-9585-6ff859f0011c.png">

any eta on the fix?

**Comment by reydd** [comment]
Hi @buckyroberts sorry for late response here, hope you guys are doing ok and stay safe. 

Hope there is a Bug bounty here ?

Thanks in Advance!

**Comment by reydd** [comment]
ping @buckyroberts

**Comment by hussu010** [comment]
Hi @reydd this might be not eligible for bug bounty since it was well known issue from the beginning with no security impact.

The are tons of endpoints in development for beta update. You'll love to test once the endpoints are live and authentication system for users are up and running. Cheers.
