### ISSUE TITLE
Make User.display_name required

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website-API#50]
make User's `display_name` required

**Comment by ThaDeveloper** [comment]
@angle943 If we're defaulting it to email does it mean this field can be blank?

**Comment by angle943** [comment]
@ThaDeveloper after talking with @buckyroberts , we we decided **not** to make it default to the `email_address`, since some people might not want to expose their email addresses publicly.

Sorry about the confusion, I must've forgotten to update the title of this issue! Lets just make the `display_name` required, without any defaults
