### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website-API#52]
We are migrating the payment & weekly reports onto the website. Ref: https://lucid.app/lucidchart/d99b8e19-220c-41b6-a93c-a64edaaf1e3d/edit?page=0_0#

Here are the tables & endpoints that needs to be created:

## Report
 - Will act as a base class.
 
```
class Report(CreatedModified):
   uuid = UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
   accomplishments = TextField(blank=True, null=True)
   next_week_goals = TextField(blank=True, null=True)
   long_term_goals = TextField(blank=True, null=True)
   concerns = TextField(blank=True, null=True)
   is_ready  = BooleanField(default=false)
   created_by = FK of the user who created the report
   audited_by = FK of the auditor who created the report
```

## CoreTeamReport

```
class CoreTeamReport(Report):
   core_team = FK of CoreTeam
```

- For a given team, there should only be one Report for a given week. There should be a BE logic that checks the `created_at` date, and if another record exists for a given team for a given week, it should error out.

Endpoints:
 - A `GET` endpoint that gives us all `CoreTeamReports` for a given week
 - `GET /core_team_reports/:uuid`
 
 - POST to `/core_team_reports` that is accessible by a Team lead (for his team) and superusers, with the given body:
```
{
    accomplishments?: string;
    next_week_goals?: string;
    long_term_goals?: string;
    concerns?: string;
    is_ready?: boolean;
}
```
 - For above, `created_by` should automatically be populated.
 
 - PATCH request to `/core_team_reports/:uuid` with the same body. Accessible only to team leads for that team and superusers.
 
 - PATCH request to `/core_team_reports/:uuid/audit` that will verify the report. Accessible only to auditors and superusers.
 
 
 ## ProjectTeamReport
 
 ```
 class ProjectTeamReport(Report):
     project_team = FK of ProjectTeam
     is_paid = BooleanField(default=False)
```

- like `CoreTeamReport`, for a given project, there should only be one report for a given week. There should be a BE logic that checks the `created_at` date, and if another record exists for a given team for a given week, it should error out.

Endpoints:
 - A `GET` endpoint that gives us all `ProjectTeamReports` for a given week
 - `GET /project_team_reports/:uuid`
 - 
 
 - POST to `/project_team_reports` that is accessible by a Team lead (for his team) and superusers, with the given body:
```
{
    accomplishments?: string;
    next_week_goals?: string;
    long_term_goals?: string;
    concerns?: string;
    is_ready?: boolean;
}
```
 - For above, `created_by` should automatically be populated.
 
 - PATCH request to `/project_team_reports/:uuid` with the same body. Accessible only to team leads for that project and superusers.
 
 - PATCH request to `/project_team_reports/:uuid/audit` that will verify the report. Accessible only to auditors and superusers.
 
 - PATCH request to `/project_team_reports/:uuid/payment` that will mark the report as paid. Accessible only to payment team and superusers.
 
 
 
 ## TeamMemberReport
 - will act as a baseClass
 
 ```
 class TeamMemberReport(CreatedModified):
    uuid = UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    accomplishments = TextField(blank=True, null=True)
    has_worked = BooleanField(default=False)
 ```
 
 ## CoreMemberReport
 
 ```
 class CoreMemberReport(TeamMemberReport):
    core_member = FK to CoreMember
    core_team_report = FK to CoreTeamReport
    is_paid = BooleanField(default=False)
 ```
 
 Endpoints:
 
 - a GET request to `/core_team_reports/:uuid/core_member_reports` to get the list of all coreMemberReports for a given `CoreTeamReport`
 - a POST request to `/core_member_reports` with the following body (creatable by superusers and TeamLeads for the given team):
 ```
 {
     accomplishments?: string;
     core_team_report: string;
     has_worked: boolean;
     (do we need core_member: string?)
 }
 ```
 - a PATCH request to `/core_member_reports/:uuid` with the following body (accessible by superuseres and TeamLeads for the given team):
 ```
 {
     has_worked?: boolean;
     accomplishments?: string;
 }
 ``` 
 - a PATCH request to `/core_member_reports/:uuid/payment` with the following body (accessible by superusers and Payment Team):
 ```
 {
     is_paid: boolean;
 }
 ```
 
  ## ProjectMemberReport
 
 ```
 class ProjectMemberReport(TeamMemberReport):
    project_member = FK to ProjectMember
    project_team_report = FK to ProjectTeamReport
 ```
 
  Endpoints:
 
 - a GET request to `/project_team_reports/:uuid/project_member_reports` to get the list of all projectMemberReports for a given `ProjectTeamReport`
 - a POST request to `/project_member_reports` with the following body (creatable by superusers and TeamLeads for the given project):
 ```
 {
     accomplishments?: string;
     project_team_report: string;
     has_worked: boolean;
     (do we need prorject_member: string?)
 }
 ```
 - a PATCH request to `/project_member_reports/:uuid` with the following body (accessible by superuseres and TeamLeads for the given project):
 ```
 {
     has_worked?: boolean;
     accomplishments?: string;
 }
 ```

**Comment by achalpatel** [comment]
@angle943 did you forgot to add start_date and end_date in the Report class as stated in the diagram or it won't be there?

**Comment by angle943** [comment]
Put a NOT READY on this, since we will change our whole payment model

**Comment by ThaDeveloper** [comment]
How long will that wait? Let me know when it's ready
