### ISSUE TITLE
move `category` field to the `playlist` model

### ISSUE THREAD

**Issue by thesanjeevsharma** [thenewboston-developers/Website-API#58]
https://github.com/thenewboston-developers/Website-API/blob/development/v1/videos/models/video.py#L22

Here, the category is added on the `video` model, but it should be on the `playlist` model instead. 

Check design for reference: [https://www.figma.com/file/tfm2m2vGTdaZT8u5iQZS3B/Youtube-Playlists?node-id=631%3A0](https://www.figma.com/file/tfm2m2vGTdaZT8u5iQZS3B/Youtube-Playlists?node-id=631%3A0)

**Comment by ThaDeveloper** [comment]
@thesanjeevsharma Since we will be getting content from youtube I went per the [documentation](https://developers.google.com/youtube/v3/docs/videos#resource) in which it's the `video` that has a category. But we can have them in both places since the data will be added manually

**Comment by thesanjeevsharma** [comment]
@ThaDeveloper In the design, I can only see playlists listed, not sure if we'll have independent videos listed. Also, the category on `video` that you get from youtube is - Gaming, Education, Kids, etc. (not 100% sure, but I think that's that). The categories we've added to playlists are different. Those are tech domains mainly. So, you are right, it will be added manually. I think we can add that field on the `playlist` model too.

@angle943

**Comment by angle943** [comment]
- We will be manually adding in our own categories, not using the one from YouTube
- Yes I believe videos can exist without a playlist. So let's have categories in both places
