### ISSUE TITLE
add filter on playlists and videos api based on `category`

### ISSUE THREAD

**Issue by thesanjeevsharma** [thenewboston-developers/Website-API#62]
Figma for reference: https://www.figma.com/file/tfm2m2vGTdaZT8u5iQZS3B/Youtube-Playlists?node-id=631%3A0

The user can select different tabs and filter out playlists/videos.

Now, to build this functionality in FE:
- When the user clicks on a tab `Python`, we would send a request to BE something like `/playlists?category=python` and it should return all the playlists that fall into this category.
- When the user clicks on the `All` tab, the request would be `/playlists`.

Add support for filters based on category. It should be optional to pass in the category.

**Comment by thesanjeevsharma** [comment]
@ThaDeveloper have a look at issue #63 before attempting this. Things might change a bit.

**Comment by ThaDeveloper** [comment]
Alright, on it @thesanjeevsharma
