### ISSUE TITLE
create a separate model for `category`

### ISSUE THREAD

**Issue by thesanjeevsharma** [thenewboston-developers/Website-API#63]
Figma for reference: https://www.figma.com/file/tfm2m2vGTdaZT8u5iQZS3B/Youtube-Playlists?node-id=631%3A0

In the design, we need to render sidebar/tabs with categories.

These categories should come from BE. Create a model for `category` and link it with `playlist` and `video` models.

**Comment by ThaDeveloper** [comment]
@thesanjeevsharma Can a playlist have more than one category, in the old setup I just completed this field has a list of categories.

**Comment by thesanjeevsharma** [comment]
Well, a playlist can have more than one category for example - `Python` and `Django`. 

But, let's hear @angle943 on this.

**Comment by angle943** [comment]
Yes, a playlist can have more than one category
