### ISSUE TITLE
Projects Model

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website-API#78]
Make the api for Projects, see design: https://www.figma.com/file/HEQpY7l2jvazLp1kqyyUiH/Projects-Page?node-id=1%3A9

*Project*
title: string
project_lead: string;
description: string;
logo: Image;
github_url: string;
overview: string;
problem: string;
target_market: string;
benefits: string;
centered_around_tnb: string;
estimated_completion_date: DATE;

*Milestone*
project: FK;
number: number;
description: string

**Comment by angle943** [comment]
@buckyroberts please leave a comment here saying you 'approve' after you have reviewed this

**Comment by ThaDeveloper** [comment]
Also, @angle943 let's specify the required fields

**Comment by buckyroberts** [comment]
Looks good to me. @ThaDeveloper all Project fields are required.
