### ISSUE TITLE
Nest the User data within GET `/core_teams`

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website-API#89]
let's nest the `User` data within `/core_teams`.

**Comment by ThaDeveloper** [comment]
@angle943 We don't have `User` in team. That's a member field

**Comment by angle943** [comment]
@ThaDeveloper here is my dilemma, what do you propose the best solution for this is?

for this page: https://thenewboston.com/teams/All/Members , we need all the user data (such as name)

if you check out here:https://github.com/thenewboston-developers/Website/pull/1663/files#diff-02db54f88bb082017197d9223213314339ed5e3167e01ad826b25b7578f38325R24

We have to first make a GET request to `/core_teams`, then for each result, we need to make GET requests to each respective user. Is there a way for the GET request to `/core_teams` to give us all this data?

**Comment by ThaDeveloper** [comment]
What user fields do you need in the core_members_meta?
