### ISSUE TITLE
Django Admin QoL improvements

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website-API#90]
1) for `Users`, lets have it display both the `email_address` and the `display name`
2) for `Core Members`, lets have it display the Core member display name, core team name, position, and `team_lead` boolean

**Comment by ThaDeveloper** [comment]
@angle943 `Core Memers` already has `job_title` and `is_lead` fields so the only fields we need to add to the return is User `display_name`and Team `name`

**Comment by ThaDeveloper** [comment]
For the user's `email` it was left out for security reasons since this is a public API @angle943 @buckyroberts

**Comment by angle943** [comment]
@ThaDeveloper this ticket was for Django Admin improvements:

1) if you look here at `Users`, you only see `email_address`, i would like to see their `display name`
![Screen Shot 2021-05-11 at 8 08 42 PM](https://user-images.githubusercontent.com/5943963/117903181-ef4a0e80-b283-11eb-847d-4f245748bec5.png)

2) For `Core Members`, this is what i see:
![Screen Shot 2021-05-11 at 8 09 31 PM](https://user-images.githubusercontent.com/5943963/117903255-0b4db000-b284-11eb-85ac-782b7899ee0f.png)
I would like this to be updated to show what I've listed above
